### ISSUE TITLE
vue: props down events up approach

### ISSUE THREAD

**Issue by ManUtopiK** [prosekit/examples#104]
Is it a choice to not use [the props down events up approach](https://levelup.gitconnected.com/props-down-events-up-in-vue-3-a-guide-to-component-communication-fd94b410c65d) in the Vue examples ?
[Another source](https://michaelnthiessen.com/pass-function-as-prop) about this pattern.

I notice that many Vue components could use this way of parent-child communication pattern. Like [this one](https://github.com/prosekit/examples/blob/master/vue-save-markdown/src/editor-component.vue), where `onDocChange` could be emitted instead of being a prop.

**Comment by ocavue** [comment]
I agree it's better to follow the best practice for each framework.

Could you check this PR https://github.com/prosekit/prosekit/pull/648  and see if everything looks good to you?
